### ISSUE TITLE
Incorporate/Store User Feedback

### ISSUE THREAD

**Issue by arm-diaz** [aws-samples/aws-genai-llm-chatbot#87] opened 2023-10-06 12:06 UTC
This is a feature request that will help customers provide feedback on the chatbot's accuracy.
For example:

- [ ] Thumbs up and down on top right corner of the response.
- [ ] If user clicks on thumbs up/down, it stores that feedback in DynamoDB under the user session table. Data could also be stored directly to S3/Athena/OpenSearch for analytics.

Any option can work as long as there is a db/storage for the feedback that can be queried later on.

**Comment by bigadsoleiman** [comment] 2023-11-02 21:24
Duplicate of #151

**Closed by bigadsoleiman** 2023-11-02 21:24 UTC
